[tool.poetry]
name = "kkloader"
version = "0.1.0"
description = "a simple deserializer / serializer for Koikatu / EmotionCreators data."
authors = ["great-majority <yosaku.ideal+github@gmail.com>"]
homepage = "https://github.com/great-majority/KoikatuCharaLoader"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
msgpack = "^1.0.2"
flake8 = "^3.9.2"
isort = "^5.9.2"
black = "^21.7b0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
