name: Check Python Code
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Lint with ruff
      run: |
        poetry run ruff check --output-format=github ./kkloader ./test
    - name: Test with pytest
      run: |
        poetry run pytest