name: Check Python Code
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 ./kkloader ./test --count --show-source --statistics
    - name: Lint with black
      run: |
        poetry run black ./kkloader ./test --check --diff
    - name: Lint with isort
      run: |
        poetry run isort ./kkloader ./test --check-only
    - name: Test with pytest
      run: |
        poetry run pytest