name: Check Python Code
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: uv sync
    - name: Lint with ruff
      run: |
        uv run ruff check --select I --output-format=github ./kkloader ./test
    - name: Test with pytest
      run: |
        uv run pytest
