name: Python check
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Lint with flake8
      run: |
        poetry run flake8 --count --show-source --statistics
    - name: Lint with black
      run: |
        poetry run black --check --diff
    - name: Lint with isort
      run: |
        poetry run isort --check-only
    - name: Test with pytest without MySQL
      run: |
        poetry run pytest